name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run tests
      run: |
        echo "Running tests..."
        # Tamara tests run karva ni commands ahi likho.
